version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  publish:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '21.7'
      - run:
          name: Auth With NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: |
            npm install
            npm publish

workflows:
  CI:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
                #            branches:
                #              only:
                #                - main
